# Generated by Django 5.2 on 2025-05-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://th.bing.com/th/id/OIP.aULahN1LnhlTmcuM_DptkAHaE9?w=215&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7', max_length=500),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('vegeterian', models.BooleanField(default=True)),
                ('picture', models.URLField(default='https://th.bing.com/th/id/OIP.aULahN1LnhlTmcuM_DptkAHaE9?w=215&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7', max_length=500)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.restaurant')),
            ],
        ),
    ]
